### ISSUE TITLE
Code not working

### ISSUE THREAD

**Issue by Harshad111** [cowbell/ionic-geofence#32]
I have downloded this code and woorked as directed but bro your code is not working in browser and also not working in android. Plz show me how  to run it in android and ios ...

**Comment by Wolf00Bomber** [comment]
Hi Harshad111, What do you mean by not working?
Is it the apk not being generated or the app feature doesn't work in android anymore?

Because i have run the following commands in the Home Directory of the project:
$ ionic platform add android
$ionic build android.
and then run the same in an android phone.

Obviously at this stage it was still not running in both Web as well as in Android.

So i checked the Console in "inspect Element" in Chrome. It seemed that some of the plugins like ionic and others are missing. So i copied the ionic folder from another project into the www/lib/ folder.

This solved the issue, and the app is running now.

Still i am seeing some other issues like the Notifications are not comming when i put the Geo Fence radius to a low value of 10 meters (I tweaked the Lib to set the min from 50 to 10 meters).

I will check for a larger radius and check in the results here.

**Comment by tsubik** [comment]
Geofence API has some limitations and I don't think it works well for radius below than 200 meters (depends on you GPS settings, wifi settings and bunch of other things I guess).
